### ISSUE TITLE
Repo development instructions incomplete

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/scitt-web#11]
need `git submodule update --init` or similar

**Comment by OR13** [comment]
sigh... I dislike hugo.

**Comment by OR13** [comment]
I prefer something simpler... built on github pages directly... like this: https://github.com/transmute-industries/respec-github-pages

I don't want to "build tool"... in my way.

**Comment by SteveLasker** [comment]
@OR13, do you want to close this out as we've confirmed the move from hugo to github pages?

**Comment by OR13** [comment]
Yes
