### ISSUE TITLE
Jekyll Template with side navigation

### ISSUE THREAD

**Issue by SteveLasker** [ietf-scitt/scitt-web#18]
The default template for github pages is overly simple, and focused on blog content.

As we have more content, such as the "What is SCITT", the libraries and the content from https://github.com/ietf-scitt/use-cases/blob/main/scitt-components.md, we'll need a more robust navigation model.

Does someone want to help with a basic left hand navigation? I'm assuming we'd need to update some file that provides the links, and not just auto-magical.

Definitely open to better design options. 
The ones I'm most familiar with are:
- [oras](oras.land)
- [helm](https://helm.sh/docs/)
- [Notary](notaryproject.dev)

**Comment by OR13** [comment]
@SteveLasker any screenshots of the kind of sidebar UI you are hoping for? I can take a stab at this.

**Comment by SteveLasker** [comment]
Thanks, @OR13 
What do you think about https://oras.land ?

**Comment by SteveLasker** [comment]
Top and side navigation, where we must add the links to a file, _and there's no magical TOC entries with even more mysterious ordering..._

**Comment by OR13** [comment]
@SteveLasker I did some experiments with storing meta data directly next to containers, a while back:

https://github.com/transmute-industries/public-credential-registry-template/blob/main/docs/public-container-registry.md

**Comment by SteveLasker** [comment]
Resolved with #21, thank you @OR13 for all the help
